### ISSUE TITLE
ToDo Release 1.1.0

### ISSUE THREAD

**Issue by ake2l** [rapiddweller/rapiddweller-benerator-ce#16]
**open topics for next release :**

- [x] Maven central upload GitHub Action (Release and Snapshots) #18
- [x] Release Notes and Release Description #19
- [x] Readme changes #19
- [x] Multi Schema description in manual #19
- [x] GraalVM description in manual #19
- [x] new release rd-lib-common
- [x] new release rd-lib-script
- [x] new release rd-lib-contiperf
- [x] new release rd-lib-format
- [x] new release rd-lib-jdbacl
